### PR TITLE
Move to jdk 8 v2

### PR DESCRIPTION
**Pull request by Nopock**
This PR updates the github actions to jdk 8 as well as converts some record classes to normal classes.

### CODE REVIEW

**Review by LaterIdiot — COMMENTED** [review]
Why only run gradle.yml on master branch?

**Comment by JxBP** [comment]
It will run when someone opens a PR to master too.

**Comment by LaterIdiot** [comment]
> It will run when someone opens a PR to master too.

Why not just run it on all projects using `on: [push, pull_request]`

**Comment by JxBP** [comment]
Well we could but when would we need to do that? We don't really have any branch that merges in another branch other than master?

**Review by unpluggedsam — APPROVED** [review]
awesome

**Pull request merged**
