### PR TITLE
Fix hypixel cosmetic enums

### PR DESCRIPTION
**Pull request by unpluggedsam**
⚫ Create a class that can find a `HypixelCosmetic` by it's JSON key (`HypixelCosmeticEnumFinder`).
  - Takes in a `HypixelCosmetic` subclass (sub-enum?)
  - Iterates through all it's enum constants
  - returns an empty `Optional` if none is found. (Most likely field does not exist in returned `JSONObject`).

⚫ Update `HypixelBedWarsStats` to use `HypixelCosmeticEnumFinder`.

⚫ Tested.

⚫ Still have to implement the rest of the methods in `HypixelBedWarsStats`.

### CODE REVIEW

**Comment by Mqlvin** [comment]
This looks good Sam.

I was just thinking, maybe it's worth it to have the `getCosmeticFromKey` method implemented into all the enums - this would mean we don't have an unknown one-method class containing the method (which may be confusing for new users), and it also means we don't have to pass the enum class in, which just makes things a bit cleaner and easier for the user of the wrapper.

We could make `HypixelCosmetic` an abstract class, and give it a method for:
- `getCosmeticFromKey` (returns the enum, as you did)
- `hasCosmeticKey` (returns true if the key is present)

What do you think of this?

**Review by NotInsertIGN — COMMENTED** [review]
Looks good, except we're not doing Novopixel.

**Comment by unpluggedsam** [comment]
> This looks good Sam.
> 
> I was just thinking, maybe it's worth it to have the `getCosmeticFromKey` method implemented into all the enums - this would mean we don't have an unknown one-method class containing the method (which may be confusing for new users), and it also means we don't have to pass the enum class in, which just makes things a bit cleaner and easier for the user of the wrapper.
> 
> We could make `HypixelCosmetic.java` an abstract class, and give it a method for:
> 
> * `getCosmeticFromKey` (returns the enum, as you did)
> * `hasCosmeticKey` (returns true if the key is present)
> * and the previous `getKey`, `getFormattedName`, `getRarity` methods
> 
> What do you think of this?

In concept, I like the idea the only problem is enums can't extend a abstract class. I'll work on implementing it into a interface.

**Comment by unpluggedsam** [comment]
4

> Looks good, except we're not doing Novopixel.

We'll have to merge the branch into this branch, shouldn't be a big deal.

**Review by NotInsertIGN — APPROVED** [review]

**Pull request merged**
